version: "3.3"

services:
  user-api:
    build:
      context: .
    image: frishi/user-service-api
    container_name: user-service-api
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3456 
    external_links:
      - mongo
      - nats
    labels:
      - traefik.http.services.user-api.loadbalancer.server.port=3456
      - traefik.enable=true
      - traefik.docker.network=gateway
      - traefik.http.routers.user-api.service=user-api@docker
      - traefik.http.routers.posts-api.rule=Host(`services.rishighan.com`) && PathPrefix(`/api/user/`)
      # - traefik.http.routers.user-api.rule=Host(`localhost`) && PathPrefix(`/api/user/`)
    networks:
      - gateway 

  user:
    build:
      context: .
    image: frishi/user-service
    container_name: user-service
    env_file: docker-compose.env
    environment:
      SERVICES: user 
    labels:
      - traefik.enable=false
    external_links:
      - mongo
      - nats
    networks:
      - gateway 

networks:
  gateway:
    external: true
