version: "3.3"

services:
  user-api:
    build:
      context: .
    image: frishi/user-service-api
    container_name: user-service-api
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3456 
    external_links:
      - mongo
      - nats
      - caddy
    networks:
      - main-network 

  user:
    build:
      context: .
    image: frishi/user-service
    container_name: user-service
    env_file: docker-compose.env
    environment:
      SERVICES: user
    external_links:
      - mongo
      - nats
      - caddy
    networks:
      - main-network 

networks:
  main-network:
    external: true
